routes/web.php
<?php
use Illuminate\Support\Facades\Route;

Route::get('/', 'HomeController@index');

Route::prefix('championnats')->group(function() {
	Route::get('/', 'ChampionnatsController@index')->name('championnats.index');
	Route::get('/nouveau', 'ChampionnatsController@add')->name('championnats.add');
	Route::post('/nouveau', 'ChampionnatsController@create');
	Route::get('/{championnat}/modifier', 'ChampionnatsController@edit')->name('championnats.edit');
	Route::post('/{championnat}/modifier', 'ChampionnatsController@update');
});

Route::prefix('epreuves')->group(function() {
	Route::get('/', 'EpreuvesController@index')->name('epreuves.index');
	Route::get('/nouveau', 'EpreuvesController@add')->name('epreuves.add');
	Route::post('/nouveau', 'EpreuvesController@create');
	Route::prefix('/{epreuve}')->group(function () {
		Route::get('/', 'GrillesController@index')->name('epreuves.show');
		Route::get('/nouveau', 'GrillesController@add')->name('grilles.add');
		Route::post('/nouveau', 'GrillesController@create');
		Route::get('/{grille}', 'GrillesController@show')->name('grilles.show');
		Route::get('/{grille}/modifier', 'GrillesController@edit')->name('grilles.edit');
		Route::post('/{grille}/modifier', 'GrillesController@update');
	});
	Route::get('/{epreuve}/modifier', 'EpreuvesController@edit')->name('epreuves.edit');
	Route::post('/{epreuve}/modifier', 'EpreuvesController@update');
});

app/Championnat.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Championnat extends Model
{
    protected $fillable = ['name', 'type'];

    public static $types = [
    	'ccp' => 'CCP Individuel 2017',
		'lns' => 'Ligue Nationale de Speedway 2017'
	];

    public function getTypeLibelleAttribute()
	{
		return self::$types[$this->type];
	}
}

app/Epreuve.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Epreuve extends Model
{
    protected $fillable = ['name', 'begin_date'];

    protected $casts = [
    	'begin_date' => 'datetime'
	];

    public function __toString()
	{
		return "{$this->name} ({$this->begin_date->format('d/m/Y')})";
	}

	public function grilles()
	{
		return $this->hasMany(Grille::class);
	}

}

app/Grille.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Grille extends Model
{
	protected $fillable = ['name', 'epreuve_id', 'championnat_id'];

	public function __toString()
	{
		return "{$this->name} - {$this->epreuve}";
	}

	public function epreuve()
	{
		return $this->belongsTo(Epreuve::class);
	}

	public function championnat()
	{
		return $this->belongsTo(Championnat::class);
	}
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/ChampionnatsController.php
<?php

namespace App\Http\Controllers;

use App\Championnat;
use Illuminate\Support\Facades\Session;

class ChampionnatsController extends Controller
{
    public function index()
	{
		$championnats = Championnat::all();
		return view('championnats.index', compact('championnats'));
	}

	public function add()
	{
		$championnat = new Championnat();
		return view('championnats.form', compact('championnat'));
	}

	public function create()
	{
		$this->validate(request(), [
			'name' => 'required',
			'type' => 'required|in:' . collect(Championnat::$types)->keys()->implode(',')
		]);

		$championnat = new Championnat(request()->all());
		$championnat->saison = 2017;

		$championnat->save();

		Session::flash('success', "Le championnat a bien été créé !");

		return redirect()->route('championnats.index');
	}

	public function edit(Championnat $championnat)
	{
		return view('championnats.form', compact('championnat'));
	}

	public function update(Championnat $championnat)
	{
		$this->validate(request(), [
			'name' => 'required',
			'type' => 'required|in:' . collect(Championnat::$types)->keys()->implode(',')
		]);

		$championnat->fill(request()->all());
		$championnat->save();

		Session::flash('success', "Le championnat {$championnat->name} a bien été modifié !");

		return redirect()->route('championnats.index');
	}
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/EpreuvesController.php
<?php

namespace App\Http\Controllers;

use App\Championnat;
use App\Epreuve;
use Carbon\Carbon;
use Illuminate\Support\Facades\Session;

class EpreuvesController extends Controller
{
    public function index()
	{
		$epreuves = Epreuve::all();
		return view('epreuves.index', compact('epreuves'));
	}

	public function add()
	{
		$epreuve = new Epreuve();
		$epreuve->begin_date = Carbon::now();
		return view('epreuves.form', compact('epreuve'));
	}

	public function create()
	{
		$this->validate(request(), [
			'name' => 'required',
			'begin_date' => 'required|date_format:d/m/Y'
		]);

		$epreuve = new Epreuve(request()->except('begin_date'));
		$epreuve->begin_date = Carbon::createFromFormat('d/m/Y', request()->get('begin_date'));
		$epreuve->save();

		Session::flash('success', "L'épreuve a bien été créée !");

		return redirect()->route('epreuves.index');
	}

	public function edit(Epreuve $epreuve)
	{
		return view('epreuves.form', compact('epreuve'));
	}

	public function update(Epreuve $epreuve)
	{
		$this->validate(request(), [
			'name'       => 'required',
			'begin_date' => 'required|date_format:d/m/Y'
		]);

		$epreuve->fill(request()->except('begin_date'));
		$epreuve->begin_date = Carbon::createFromFormat('d/m/Y', request()->get('begin_date'));
		$epreuve->save();

		Session::flash('success', "L'épreuve {$epreuve->name} a bien été modifiée !");

		return redirect()->route('epreuves.index');
	}

	public function show(Epreuve $epreuve)
	{
		return view('epreuves.show', compact('epreuve'));
	}
}

app/Http/Controllers/GrillesController.php
<?php

namespace App\Http\Controllers;

use App\Championnat;
use App\Epreuve;
use App\Grille;
use Carbon\Carbon;
use Illuminate\Support\Facades\Session;

class GrillesController extends Controller
{
	public function index(Epreuve $epreuve)
	{
		$grilles = $epreuve->grilles;
		return view('grilles.index', compact('epreuve', 'grilles'));
	}

	public function add(Epreuve $epreuve)
	{
		$grille = new Grille();
		$grille->epreuve_id = $epreuve->id;

		$championnats = array_merge(['0' => 'Aucun'], Championnat::all()->pluck('name', 'id')->toArray());
		return view('grilles.form', compact('epreuve', 'grille', 'championnats'));
	}

	public function create(Epreuve $epreuve)
	{
		$this->validate(request(), [
			'name'           => 'required',
			//'championnat_id' => 'exists:championnats,id',
		]);

		$grille = new Grille(request()->all());
		$grille->epreuve_id = $epreuve->id;
		$grille->save();

		Session::flash('success', "La grille a bien été créée !");

		return redirect()->route('epreuves.show', $epreuve);
	}

	public function edit(Epreuve $epreuve, Grille $grille)
	{
		$championnats = array_merge(['0' => 'Aucun'], Championnat::all()->pluck('name', 'id')->toArray());

		return view('grilles.form', compact('grille', 'epreuve', 'championnats'));
	}

	public function update(Epreuve $epreuve, Grille $grille)
	{
		$this->validate(request(), [
			'name' => 'required',
			//'championnat_id' => 'exists:championnats,id',
		]);

		$grille->fill(request()->all());
		$grille->save();

		Session::flash('success', "La grille {$grille->name} a bien été modifiée !");

		return redirect()->route('epreuves.show', $epreuve);
	}

	public function show(Epreuve $epreuve)
	{
		return view('grilles.show', compact('epreuve'));
	}
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    public function index()
	{
		return view('index');
	}
}

resources/views/app.blade.php
@extends('skeleton')

@section('body')
    <div class="app-container"><!-- START APP HEADER -->
        <div class="app-header app-header-design-dark">
            <div class="container container-boxed">
                <ul class="app-header-buttons visible-mobile">
                    <li><a href="#" class="btn btn-link btn-icon" data-navigation-horizontal-toggle="true"><span
                                    class="icon-menu"></span></a></li>
                </ul>
                <a href="index.html" class="app-header-logo app-header-logo-light app-header-logo-condensed">Project</a>
                <ul class="app-header-buttons pull-right">
                    <li><a href="#" class="btn btn-link btn-icon"><span class="icon-cog"></span></a></li>
                    <li><a href="#" class="btn btn-default">Log Out</a></li>
                </ul>
            </div>
        </div><!-- END APP HEADER  --><!-- START APP CONTENT -->
        <div class="app-content">
            <div class="app-navigation-horizontal margin-bottom-15">
                <div class="container container-boxed">
                    <nav>
                        <ul>
                            <li class="openable {{ Request::is('/') || Request::is('championnats*') || (Request::is('epreuves') && !Request::is('epreuves/*')) ? 'active' : '' }}"><a href="#"><span class="fa fa-gear"></span> Paramètrage</a>
                                <ul>
                                    <li class="{{ Request::is('/') ? 'active' : '' }}">
                                        <a href="{{ url('/') }}">
                                            <i class="fa fa-home"></i> Accueil
                                        </a>
                                    </li>
                                    <li class="{{ Request::is('championnats*') ? 'active' : '' }}">
                                        <a href="{{ route('championnats.index') }}">
                                            <i class="fa fa-trophy"></i> Championnats
                                        </a>
                                    </li>
                                    <li class="{{ Request::is('epreuves') && !Request::is('epreuves/*') ? 'active' : '' }}">
                                        <a href="{{ route('epreuves.index') }}">
                                            <i class="fa fa-calendar"></i> Épreuves
                                        </a>
                                    </li>

                                </ul>
                            @if (Request::is('epreuves*') && !Request::is('epreuves') && isset($epreuve))
                                <li class="openable active">
                                    <a href="#"><span class="fa fa-calendar"></span> {{ $epreuve }}</a>
                                    <ul>
                                        <li class="{{ Request::is('epreuves/' . $epreuve->id) ? 'active' : '' }}">
                                            <a href="{{ route('epreuves.show', $epreuve) }}">
                                                <i class="fa fa-table"></i> Grilles
                                            </a>
                                        </li>
                                    </ul>
                                @endif
                            </li>
                        </ul>
                    </nav>
                </div>
            </div><!-- START PAGE CONTAINER -->
            <div class="container container-boxed">
                @include('flashbag')
                @yield('content')
            </div>
        </div>
    </div>
@endsection

resources/views/championnats/form.blade.php
@extends('app')
@section('title', "Championnats")

@section('content')
    <div class="block block-condensed">
        <div class="app-heading app-heading-small">
            <div class="title">
                <h2>
                    @if ($championnat->exists())
                        Modifier un Championnat
                    @else
                        Nouveau Championnat
                    @endif
                </h2>
                </div>
        </div>
        <div class="block-content">

            {!! Form::open(['url' => URL::full()]) !!}
            <div class="form-group">
                <label class="col-md-3 control-label">
                    Nom
                </label>
                <div class="col-md-9">
                    {{ Form::text('name', old('name', $championnat->name), ['class' => 'form-control']) }}
                </div>
            </div>

            <div class="form-group">
                <label class="col-md-3 control-label">
                    Type de Championnat
                </label>
                <div class="col-md-9">
                    {{ Form::select('type', \App\Championnat::$types, old('type', $championnat->type), ['class' => 'form-control bs-select']) }}
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-9 col-md-offset-3">
                    <button type="submit" class="btn btn-primary">
                        <i class="fa fa-save"></i> Enregistrer
                    </button>
                </div>
            </div>
            {!! Form::close() !!}

        </div>
    </div>
@endsection

resources/views/championnats/index.blade.php
@extends('app')
@section('title', "Championnats")

@section('content')
    <div class="block block-condensed">
        <div class="app-heading app-heading-small">
            <div class="title"><h2>Championnats</h2>
                <p>Liste des Championnats</p></div>
            <div class="heading-elements">
                <a href="{{ route('championnats.add') }}" class="btn btn-success btn-clean">
                    <i class="fa fa-plus"></i> Nouveau Championnat
                </a>
            </div>
        </div>
        <div class="block-content padding-0 margin-bottom-0 table-responsive">
            <table class="table margin-bottom-0">
                <thead>
                <tr>
                    <th>Nom</th>
                    <th>Type</th>
                    <th>Actions</th>
                </tr>
                </thead>
                <tbody>
                @forelse ($championnats as $championnat)
                    <tr>
                        <td>
                            {{ $championnat->name }}
                        </td>
                        <td>
                            {{ $championnat->type_libelle }}
                        </td>
                        <td>
                            <a href="{{ route('championnats.edit', $championnat) }}" class="btn btn-info btn-clean btn-xs">
                                <i class="fa fa-pencil"></i> Modifier
                            </a>
                        </td>
                    </tr>
                @empty
                    <tr>
                        <td colspan="3" class="text-center lead text-muted">
                            Aucun championnat
                        </td>
                    </tr>
                @endforelse
                </tbody>
            </table>
        </div>
    </div>
@endsection

resources/views/epreuves/form.blade.php
@extends('app')
@section('title', "Épreuves")

@section('content')
    <div class="block block-condensed">
        <div class="app-heading app-heading-small">
            <div class="title">
                <h2>
                    @if ($epreuve->exists())
                        Modifier une Épreuve
                    @else
                        Nouvelle Épreuve
                    @endif
                </h2>
                </div>
        </div>
        <div class="block-content">

            {!! Form::open(['url' => URL::full()]) !!}
            <div class="form-group">
                <label class="col-md-3 control-label">
                    Nom
                </label>
                <div class="col-md-9">
                    {{ Form::text('name', old('name', $epreuve->name), ['class' => 'form-control']) }}
                </div>
            </div>

            <div class="form-group">
                <label class="col-md-3 control-label">
                    Date de début
                </label>
                <div class="col-md-9">
                    {{ Form::text('begin_date', old('begin_date', $epreuve->begin_date->format('d/m/Y')), ['class' => 'form-control bs-datepicker', 'placeholder' => 'JJ/MM/AAAA']) }}
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-9 col-md-offset-3">
                    <button type="submit" class="btn btn-primary">
                        <i class="fa fa-save"></i> Enregistrer
                    </button>
                </div>
            </div>
            {!! Form::close() !!}

        </div>
    </div>
@endsection

resources/views/epreuves/index.blade.php
@extends('app')
@section('title', "Épreuves")

@section('content')
    <div class="block block-condensed">
        <div class="app-heading app-heading-small">
            <div class="title"><h2>Épreuves</h2>
                <p>Liste des Épreuves</p></div>
            <div class="heading-elements">
                <a href="{{ route('epreuves.add') }}" class="btn btn-success btn-clean">
                    <i class="fa fa-plus"></i> Nouvelle épreuve
                </a>
            </div>
        </div>
        <div class="block-content padding-0 margin-bottom-0 table-responsive">
            <table class="table margin-bottom-0">
                <thead>
                <tr>
                    <th>Nom</th>
                    <th>Date</th>
                    <th>Actions</th>
                </tr>
                </thead>
                <tbody>
                @forelse ($epreuves as $epreuve)
                    <tr>
                        <td>
                            <a href="{{ route('epreuves.show', $epreuve) }}" class="text-bold">
                                {{ $epreuve->name }}
                            </a>
                        </td>
                        <td>
                            {{ $epreuve->begin_date->formatLocalized('%A %d %B %Y') }}
                        </td>
                        <td>
                            <a href="{{ route('epreuves.edit', $epreuve) }}" class="btn btn-info btn-clean btn-xs">
                                <i class="fa fa-pencil"></i> Modifier
                            </a>
                        </td>
                    </tr>
                @empty
                    <tr>
                        <td colspan="3" class="text-center lead text-muted">
                            Aucune épreuve
                        </td>
                    </tr>
                @endforelse
                </tbody>
            </table>
        </div>
    </div>
@endsection

resources/views/flashbag.blade.php
@if (Session::has('success'))
    <div class="alert alert-success alert-icon-block alert-dismissible" role="alert">
        <div class="alert-icon">
            <i class="fa fa-check-circle"></i>
        </div>
        {!! Session::get('success') !!}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span class="fa fa-times"></span>
        </button>
    </div>
@endif

@if (isset($errors) && !$errors->isEmpty())
    <div class="alert alert-danger alert-icon-block" role="alert">
        <div class="alert-icon">
            <i class="fa fa-exclamation-triangle"></i>
        </div>
        @foreach ($errors->all() as $error)
            {{ $error }}<br>
        @endforeach
    </div>
@endif

resources/views/grilles/form.blade.php
@extends('app')
@section('title', $epreuve)

@section('content')
    <div class="block block-condensed">
        <div class="app-heading app-heading-small">
            <div class="title">
                <h2>
                    @if ($epreuve->exists())
                        Modifier les propriétés d'une Grille
                    @else
                        Nouvelle Grille
                    @endif
                </h2>
                </div>
        </div>
        <div class="block-content">

            {!! Form::open(['url' => URL::full()]) !!}
            <div class="form-group">
                <label class="col-md-3 control-label">
                    Nom
                </label>
                <div class="col-md-9">
                    {{ Form::text('name', old('name', $grille->name), ['class' => 'form-control']) }}
                </div>
            </div>

            <div class="form-group">
                <label class="col-md-3 control-label">
                    Championnat
                </label>
                <div class="col-md-9">
                    {{ Form::select('championnat_id', $championnats, old('championnat_id', $grille->championnat_id), ['class' => 'form-control bs-select']) }}
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-9 col-md-offset-3">
                    <button type="submit" class="btn btn-primary">
                        <i class="fa fa-save"></i> Enregistrer
                    </button>
                </div>
            </div>
            {!! Form::close() !!}

        </div>
    </div>
@endsection

resources/views/grilles/index.blade.php
@extends('app')
@section('title', $epreuve)

@section('content')
    <div class="block block-condensed">
        <div class="app-heading app-heading-small">
            <div class="title">
                <h2>
                    Grilles
                </h2>
            </div>
            <div class="heading-elements">
                <a href="{{ route('grilles.add', $epreuve) }}" class="btn btn-success btn-clean">
                    <i class="fa fa-plus"></i> Nouvelle Grille
                </a>
            </div>
        </div>
        <div class="block-content padding-0 margin-bottom-0 table-responsive">
            <table class="table margin-bottom-0">
                <thead>
                <tr>
                    <th>Nom</th>
                    <th>Championnat</th>
                </tr>
                </thead>
                <tbody>
                @forelse ($grilles as $grille)
                    <tr>
                        <td>
                            <a href="{{ route('grilles.show', [$epreuve, $grille]) }}" class="text-bold">
                                {{ $grille->name }}
                            </a>
                        </td>
                        <td>
                            {{ $grille->champopnnat->name ?? 'Aucun' }}
                        </td>
                        <td>
                            <a href="{{ route('grilles.edit', [$epreuve, $grille]) }}"
                               class="btn btn-info btn-clean btn-xs">
                                <i class="fa fa-pencil"></i> Modifier
                            </a>
                        </td>
                    </tr>
                @empty
                    <tr>
                        <td colspan="3" class="text-center lead text-muted">
                            Aucune grille
                        </td>
                    </tr>
                @endforelse
                </tbody>
            </table>
        </div>
    </div>
@endsection

resources/views/grilles/show.blade.php
@extends('app')
@section('title', $epreuve)

@section('content')
    <div class="block block-condensed">
        <div class="app-heading app-heading-small">
            <div class="title">
                <h2>
                    Grilles
                </h2>
            </div>
            <div class="heading-elements">
                <a href="{{ route('grilles.add', $epreuve) }}" class="btn btn-success btn-clean">
                    <i class="fa fa-plus"></i> Nouvelle Grille
                </a>
            </div>
        </div>
        <div class="block-content padding-0 margin-bottom-0 table-responsive">
            <table class="table margin-bottom-0">
                <thead>
                <tr>
                    <th>Nom</th>
                    <th>Championnat</th>
                </tr>
                </thead>
                <tbody>
                @forelse ($grilles as $grille)
                    <tr>
                        <td>
                            <a href="{{ route('grilles.show', [$epreuve, $grille]) }}" class="text-bold">
                                {{ $grille->name }}
                            </a>
                        </td>
                        <td>
                            {{ $grille->champopnnat->name ?? 'Aucun' }}
                        </td>
                        <td>
                            <a href="{{ route('grilles.edit', [$epreuve, $grille]) }}" class="btn btn-info btn-clean btn-xs">
                                <i class="fa fa-pencil"></i> Modifier
                            </a>
                        </td>
                    </tr>
                @empty
                    <tr>
                        <td colspan="3" class="text-center lead text-muted">
                            Aucune grille
                        </td>
                    </tr>
                @endforelse
                </tbody>
            </table>
        </div>
    </div>
@endsection

resources/views/skeleton.blade.php
<!DOCTYPE html>
<html lang="fr">
<head>
    <title>@yield('title') - Résultats CCP</title>

    <!-- META SECTION -->
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    {{--<link rel="shortcut icon" href="favicon.ico" type="image/x-icon">--}}
    {{--<link rel="icon" href="favicon.ico" type="image/x-icon">--}}
    <!-- END META SECTION -->
    <link rel="stylesheet" href="{{ asset('css/style.css') }}">
    @stack('styles')
</head>
<body>

<!-- APP WRAPPER -->
<div class="app">

    @yield('body')

</div>
<!-- END APP WRAPPER -->

<script type="text/javascript" src="{{ asset('js/vendor/jquery/jquery.min.js') }}"></script>
<script type="text/javascript" src="{{ asset('js/vendor/jquery/jquery-ui.min.js') }}"></script>
<script type="text/javascript" src="{{ asset('js/vendor/bootstrap/bootstrap.min.js') }}"></script>
<script type="text/javascript" src="{{ asset('js/vendor/moment/moment.min.js') }}"></script>
<script type="text/javascript" src="{{ asset('js/vendor/bootstrap-select/bootstrap-select.js') }}"></script>
<script type="text/javascript" src="{{ asset('js/app.js') }}"></script>
<script type="text/javascript" src="{{ asset('js/app_plugins.js') }}"></script>
@stack('scripts')
</body>
</html>